// import { useContext } from 'react'

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";

import { App } from '@/app/_components/App'
import { Navigation } from '@/app/_components/Navigation'

import "./globals.css";
import styles from "./page.module.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

interface IProps {
  children: React.ReactNode
}

export default function RootLayout({
  children,
}: IProps) {
  // const { isAuthenticated } = useContext(AuthenticationContext);
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <App>
          <Navigation />
          <main className={styles.main}>
        {children}
          </main>
        </App>
      </body>
    </html>
  );
}
